functionsDirectory = "/Users/gianluca.vedovato/Sites/prsnl/pedro/dist/netlify/functions"
functionsDirectoryOrigin = "config"
plugins = []
headers = []
redirects = []

[build]
publish = "/Users/gianluca.vedovato/Sites/prsnl/pedro"
publishOrigin = "config"
commandOrigin = "config"
command = "npm run build:functions"
functions = "/Users/gianluca.vedovato/Sites/prsnl/pedro/dist/netlify/functions"

[build.environment]

[build.processing]

[build.processing.css]

[build.processing.html]

[build.processing.images]

[build.processing.js]

[build.services]

[functions]

[functions.telegram-webhook]
node_bundler = "esbuild"
external_node_modules = ["@supabase/supabase-js"]

[functions.telegram-webhook-local]
node_bundler = "esbuild"

[functions.status-check]
node_bundler = "esbuild"

[functions.keep-alive]
node_bundler = "esbuild"

[functions."*"]
node_bundler = "esbuild"