[functions]
  # Usa direttamente la sorgente TypeScript; Netlify compila con esbuild
  directory = "netlify/functions"
  node_bundler = "esbuild"

[build]
  # Nessun build custom necessario per le Functions; esbuild gestisce TS automaticamente
  publish = "."

[functions."telegram-webhook"]
  node_bundler = "esbuild"
  external_node_modules = ["@supabase/supabase-js"]

[functions."telegram-webhook-local"]
  node_bundler = "esbuild"

[functions."rules-pdf"]
  node_bundler = "esbuild"
  external_node_modules = ["@supabase/supabase-js", "@sparticuz/chromium", "puppeteer-core"]


[[redirects]]
  from = "/regolamento.pdf"
  to = "/.netlify/functions/rules-pdf"
  status = 200


